### ISSUE TITLE
1st step in loading vdj data

### ISSUE THREAD

**Issue by taopeng1100** [veghp/pyVDJ#3] opened 2020-02-25 23:52 UTC
Hi I am a big fan of Scanpy so I am so eager to try your pyvdj to link vdj data to 5' GEX data in Scanpy. I am not sure that I can follow the instruction in your tutorial using manifest? Can you help me in setting up matching one vdj sample to one 5'GEX sample?

Thx,

Tao

**Comment by veghp** [comment] 2020-02-26 00:23
Sure. Does my reply here help?
https://github.com/veghp/pyVDJ/issues/2#issuecomment-591116141

**Comment by taopeng1100** [comment] 2020-02-26 00:46
My adata.obs does not have metadata?

AnnData object with n_obs × n_vars = 4187 × 1475 obs: 'n_genes', 'percent_mito', 'n_counts', 'leiden' var: 'gene_ids', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm' uns: 'leiden', 'leiden_colors', 'neighbors', 'pca', 'rank_genes_groups' obsm: 'X_pca', 'X_umap' varm: 'PCs'

So when I run the following codes:
paths = './VDJ_TK_cx_8wks_191106' + manifest['VDJ_TK_cx_8wks_191106'] + '/filtered_contig_annotations.csv'
samples = dict(paths, adata.obs['metadata'])

I go the error like this:

KeyError Traceback (most recent call last) ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance) 2656 try: -> 2657 return self._engine.get_loc(key) 2658 except KeyError: pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc() pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc() pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item() pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item() KeyError: 'metadata' During handling of the above exception, another exception occurred: KeyError Traceback (most recent call last) <ipython-input-23-83f2f5a1ec0a> in <module> ----> 1 samples = dict(paths, adata.obs['metadata']) ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key) 2925 if self.columns.nlevels > 1: 2926 return self._getitem_multilevel(key) -> 2927 indexer = self.columns.get_loc(key) 2928 if is_integer(indexer): 2929 indexer = [indexer] ~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance) 2657 return self._engine.get_loc(key) 2658 except KeyError: -> 2659 return self._engine.get_loc(self._maybe_cast_indexer(key)) 2660 indexer = self.get_indexer([key], method=method, tolerance=tolerance) 2661 if indexer.ndim > 1 or indexer.size > 1: pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc() pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc() pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item() pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item() KeyError: 'metadata'


I am sorry to annoy you like this! I only have basic Python skills.

Tao

**Comment by veghp** [comment] 2020-02-26 10:35
Well, yes using this package requires some scripting knowledge. My suggestion was to skip the manifest part. Also note that the code you ran is different in multiple ways from the one in the tutorial.

Try:

    samples = {
        'VDJ_TK_cx_8wks_191106/filtered_contig_annotations.csv': 'yoursampleid1',
    }

Then make a column in `adata.obs['vdj_obs']` which has:
cellbarcode1_yoursampleid1
cellbarcode2_yoursampleid1
cellbarcode5_yoursampleid2
...

You can get the cellbarcodes from `adata.obs_names`. If you have only one sample, then you can try

    cellnames = adata.obs_names
    cellbarcode = cellnames.str.split("-").str[:2].str.join("-") # cell barcode part + '-1'
    adata.obs['vdj_obs'] = cellbarcode.astype(str) + "_" + 'yoursampleid1'

**Comment by taopeng1100** [comment] 2020-02-27 19:26
I successfully loaded the data by following your codes above. But I got the error message in plotting step:

AttributeError                            Traceback (most recent call last)
<ipython-input-37-890a35edda91> in <module>
      1 sc.settings.set_figure_params(dpi=70)
----> 2 sc.pl.umap(adata, color=['vdj_has_vdjdata', 'vdj_is_clone'])

~\AppData\Local\Continuum\anaconda3\lib\site-packages\scanpy\plotting\_tools\scatterplots.py in umap(adata, **kwargs)
    297     If `show==False` a :class:`~matplotlib.axes.Axes` or a list of it.
    298     """
--> 299     return plot_scatter(adata, 'umap', **kwargs)
    300 
    301 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\scanpy\plotting\_tools\scatterplots.py in plot_scatter(adata, basis, color, gene_symbols, use_raw, sort_order, edges, edges_width, edges_color, arrows, arrows_kwds, groups, components, layer, projection, color_map, palette, size, frameon, legend_fontsize, legend_fontweight, legend_loc, legend_fontoutline, ncols, hspace, wspace, title, show, save, ax, return_fig, **kwargs)
    258         return fig
    259     axs = axs if multi_panel else ax
--> 260     utils.savefig_or_show(basis, show=show, save=save)
    261     if show is False:
    262         return axs

~\AppData\Local\Continuum\anaconda3\lib\site-packages\scanpy\plotting\_utils.py in savefig_or_show(writekey, show, dpi, ext, save)
    250     save = settings.autosave if save is None else save
    251     show = settings.autoshow if show is None else show
--> 252     if save: savefig(writekey, dpi=dpi, ext=ext)
    253     if show: pl.show()
    254     if save: pl.close()  # clear figure

~\AppData\Local\Continuum\anaconda3\lib\site-packages\scanpy\plotting\_utils.py in savefig(writekey, dpi, ext)
    233     # output the following msg at warning level; it's really important for the user
    234     logg.warning(f'saving figure to file {filename}')
--> 235     pl.savefig(filename, dpi=dpi, bbox_inches='tight')
    236 
    237 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\pyplot.py in savefig(*args, **kwargs)
    687             num = get_fignums()[allLabels.index(fig)]
    688             _pylab_helpers.Gcf.destroy(num)
--> 689     elif isinstance(fig, Figure):
    690         _pylab_helpers.Gcf.destroy_fig(fig)
    691     else:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\figure.py in savefig(self, fname, frameon, transparent, **kwargs)
   2092             The facecolor of the figure; if *None*, defaults to
   2093             :rc:`savefig.facecolor`.
-> 2094 
   2095         edgecolor : color spec or None, optional
   2096             The edgecolor of the figure; if *None*, defaults to

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, **kwargs)
   2004                 filename = os.fspath(filename)
   2005             if isinstance(filename, str):
-> 2006                 format = os.path.splitext(filename)[1][1:]
   2007             if format is None or format == '':
   2008                 format = self.get_default_filetype()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\backend_bases.py in _get_output_canvas(self, fmt)
   1940         """
   1941         Return a canvas suitable for saving figures to a specified file format.
-> 1942 
   1943         If necessary, this function will switch to a registered backend that
   1944         supports the format.

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\backend_bases.py in get_registered_canvas_class(format)
    120     """
    121     if format not in _default_backends:
--> 122         return None
    123     backend_class = _default_backends[format]
    124     if isinstance(backend_class, str):

~\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap_external.py in exec_module(self, module)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\backends\backend_pdf.py in <module>
    421 
    422 
--> 423 class PdfFile(object):
    424     """PDF file object."""
    425 

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\backends\backend_pdf.py in PdfFile()
    654 
    655     @cbook.deprecated("3.0")
--> 656     @property
    657     def texFontMap(self):
    658         # lazy-load texFontMap, it takes a while to parse

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py in deprecate(obj, message, name, alternative, pending, addendum)
    180                 pass
    181     """
--> 182 
    183     def deprecate(obj, message=message, name=name, alternative=alternative,
    184                   pending=pending, obj_type=obj_type, addendum=addendum):

AttributeError: 'property' object has no attribute '__name__'

**Comment by taopeng1100** [comment] 2020-02-27 19:51
These are the steps I used to load the data:
samples = {
    'VDJ_TK_cx_8wks_191106/filtered_contig_annotations.csv': 'TK_cx_8wksPH_191106'
}

adata = pyvdj.load_vdj(samples, adata, obs_col='vdj_obs', cellranger=3)

adata = pyvdj.add_obs(adata, obs=['clonotype', 'is_clone'])

**Comment by veghp** [comment] 2020-02-27 20:28
It should work. Are you in the correct directory, where 'VDJ_TK_cx_8wks_191106/filtered_contig_annotations.csv' is?

You can check what's in the adata by running:
`adata.obs_names`
`adata.uns.['pyvdj']['df'].columns`

These two should have matching entries:
`adata.uns.['pyvdj']['df']['barcode_meta']`
`adata.obs['vdj_obs']`

Annotations:
`adata.obs['vdj_has_vdjdata']`
`adata.obs['vdj_is_clone']`

**Comment by taopeng1100** [comment] 2020-02-27 21:15
Hi I put the filtered_contig_annotations.csv file in the same folder “TK_cx_8wksPH_191106 from  which I generate adata.

The same error message like last time.

I can see all the cell barcodes by running: adata.obs_names

But I can’t run these lines of codes:
adata.uns.['pyvdj']['df'].columns ??

adata.uns.['pyvdj']['df']['barcode_meta']??


Thx!

Tao

**Comment by veghp** [comment] 2020-02-27 22:58
There was an extra dot. Try:

`adata.uns['pyvdj']['df'].columns`
`adata.uns['pyvdj']['df']['barcode_meta']`

**Comment by taopeng1100** [comment] 2020-02-27 23:11
When running: adata.uns['pyvdj']['df']['barcode_meta']
Output is like this:
0 AAACCTGAGGGATGGG-1_TK_cx_8wksPH_191106
1 AAACCTGAGGGATGGG-1_TK_cx_8wksPH_191106
2 AAACCTGAGTACGCGA-1_TK_cx_8wksPH_191106
Name: barcode_meta, Length: 7026, dtype: object

When adata.obs['vdj_obs']
Output is like:
index
AAACCTGAGGGATGGG-1 AAACCTGAGGGATGGG-1_TK_cx_8wksPH_191106
AAACCTGAGTACGCGA-1 AAACCTGAGTACGCGA-1_TK_cx_8wksPH_191106
AAACCTGCAGCATACT-1 AAACCTGCAGCATACT-1_TK_cx_8wksPH_191106

Not sure this is the right match?

**Comment by taopeng1100** [comment] 2020-02-27 23:16
When running : adata.obs['vdj_obs']:

Output is like this:
index
AAACCTGAGGGATGGG-1    AAACCTGAGGGATGGG-1_TK_cx_8wksPH_191106
AAACCTGAGTACGCGA-1    AAACCTGAGTACGCGA-1_TK_cx_8wksPH_191106

Name: vdj_obs, Length: 4187, dtype: object

**Comment by taopeng1100** [comment] 2020-02-27 23:19
When running adata.uns['pyvdj']['df'].columns,

output:
Index(['barcode', 'is_cell', 'contig_id', 'high_confidence', 'length', 'chain',
       'v_gene', 'd_gene', 'j_gene', 'c_gene', 'full_length', 'productive',
       'cdr3', 'cdr3_nt', 'reads', 'umis', 'raw_clonotype_id',
       'raw_consensus_id', 'barcode_meta', 'clonotype_meta', 'sample',
       'productive_all', 'productive_any'],
      dtype='object')

**Comment by taopeng1100** [comment] 2020-02-27 23:22
When running adata.obs_names, output is:
Index(['AAACCTGAGGGATGGG-1', 'AAACCTGAGTACGCGA-1', 'AAACCTGCAGCATACT-1',
       'AAACCTGCAGTATCTG-1', 'AAACCTGCAGTTAACC-1', 'AAACCTGGTAAACGCG-1',
       'AAACCTGGTACAGTTC-1', 'AAACCTGGTTCGGCAC-1', 'AAACCTGTCGCCATAA-1',
       'AAACCTGTCTGCTGCT-1',
       ...
       'TTTGGTTTCAGTTCGA-1', 'TTTGGTTTCTCCTATA-1', 'TTTGTCAAGAACTGTA-1',
       'TTTGTCAAGAAGGGTA-1', 'TTTGTCAAGCTGATAA-1', 'TTTGTCACATTAGGCT-1',
       'TTTGTCAGTACGACCC-1', 'TTTGTCAGTCAAGCGA-1', 'TTTGTCAGTGATGATA-1',
       'TTTGTCATCCACTGGG-1'],
      dtype='object', name='index', length=4187)

**Comment by veghp** [comment] 2020-02-27 23:37
Yes, the cell names seem to match. Another suggestion above was to check:
`adata.obs['vdj_has_vdjdata']`
`adata.obs['vdj_is_clone']`
To see these were indeed made in adata. Or try adata.obs.columns to list column names

**Comment by taopeng1100** [comment] 2020-02-27 23:40
When running adata.obs['vdj_has_vdjdata'], output:
index
AAACCTGAGGGATGGG-1     True
AAACCTGAGTACGCGA-1     True
AAACCTGCAGCATACT-1    False
AAACCTGCAGTATCTG-1    False
AAACCTGCAGTTAACC-1     True
AAACCTGGTAAACGCG-1    False
Name: vdj_has_vdjdata, Length: 4187, dtype: bool

When running  adata.obs['vdj_is_clone'], output:
index
AAACCTGAGGGATGGG-1    False
AAACCTGAGTACGCGA-1     True
AAACCTGCAGCATACT-1    False
AAACCTGCAGTATCTG-1    False
AAACCTGCAGTTAACC-1     True
AAACCTGGTAAACGCG-1    False
AAACCTGGTACAGTTC-1     True
AAACCTGGTTCGGCAC-1    False
Name: vdj_is_clone, Length: 4187, dtype: bool

**Comment by taopeng1100** [comment] 2020-02-27 23:46
The codes are like these:
samples = {
    'TK_cx_8wksPH_191106/filtered_contig_annotations.csv': 'TK_cx_8wksPH_191106'
}
cellnames = adata.obs_names
cellbarcode = cellnames.str.split("-").str[:2].str.join("-") # cell barcode part + '-1'
adata.obs['vdj_obs'] = cellbarcode.astype(str) + "_" + 'TK_cx_8wksPH_191106'
adata = pyvdj.load_vdj(samples, adata, obs_col='vdj_obs', cellranger=3)
adata = pyvdj.add_obs(adata, obs=['clonotype', 'is_clone'])
sc.settings.set_figure_params(dpi=70)
sc.pl.umap(adata, color=['vdj_has_vdjdata', 'vdj_is_clone'])

**Comment by veghp** [comment] 2020-02-27 23:58
That looks fine. You have the annotation you want to plot. You also seem to have calculated UMAP. Can you plot something else, like 'leiden'?
Perhaps changing the annotation to categorical will help:
`adata.obs['vdj_has_vdjdata'] = adata.obs['vdj_has_vdjdata'].astype('category')`

**Comment by taopeng1100** [comment] 2020-02-28 00:03
I run this code: sc.pl.umap(adata, color=['vdj_has_vdjdata', 'vdj_is_clone','leiden'])

The output error is:

WARNING: saving figure to file figures\umap.pdf
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-102-f8eafb6b1ea8> in <module>
----> 1 sc.pl.umap(adata, color=['vdj_has_vdjdata', 'vdj_is_clone','leiden'])

~\AppData\Local\Continuum\anaconda3\lib\site-packages\scanpy\plotting\_tools\scatterplots.py in umap(adata, **kwargs)
    297     If `show==False` a :class:`~matplotlib.axes.Axes` or a list of it.
    298     """
--> 299     return plot_scatter(adata, 'umap', **kwargs)
    300
    301

~\AppData\Local\Continuum\anaconda3\lib\site-packages\scanpy\plotting\_tools\scatterplots.py in plot_scatter(adata, basis, color, gene_symbols, use_raw, sort_order, edges, edges_width, edges_color, arrows, arrows_kwds, groups, components, layer, projection, color_map, palette, size, frameon, legend_fontsize, legend_fontweight, legend_loc, legend_fontoutline, ncols, hspace, wspace, title, show, save, ax, return_fig, **kwargs)
    258         return fig
    259     axs = axs if multi_panel else ax
--> 260     utils.savefig_or_show(basis, show=show, save=save)
    261     if show is False:
    262         return axs

~\AppData\Local\Continuum\anaconda3\lib\site-packages\scanpy\plotting\_utils.py in savefig_or_show(writekey, show, dpi, ext, save)
    250     save = settings.autosave if save is None else save
    251     show = settings.autoshow if show is None else show
--> 252     if save: savefig(writekey, dpi=dpi, ext=ext)
    253     if show: pl.show()
    254     if save: pl.close()  # clear figure

~\AppData\Local\Continuum\anaconda3\lib\site-packages\scanpy\plotting\_utils.py in savefig(writekey, dpi, ext)
    233     # output the following msg at warning level; it's really important for the user
    234     logg.warning(f'saving figure to file {filename}')
--> 235     pl.savefig(filename, dpi=dpi, bbox_inches='tight')
    236
    237

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\pyplot.py in savefig(*args, **kwargs)
    687             num = get_fignums()[allLabels.index(fig)]
    688             _pylab_helpers.Gcf.destroy(num)
--> 689     elif isinstance(fig, Figure):
    690         _pylab_helpers.Gcf.destroy_fig(fig)
    691     else:

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\figure.py in savefig(self, fname, frameon, transparent, **kwargs)
   2092             The facecolor of the figure; if *None*, defaults to
   2093             :rc:`savefig.facecolor`.
-> 2094
   2095         edgecolor : color spec or None, optional
   2096             The edgecolor of the figure; if *None*, defaults to

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, **kwargs)
   2004                 filename = os.fspath(filename)
   2005             if isinstance(filename, str):
-> 2006                 format = os.path.splitext(filename)[1][1:]
   2007             if format is None or format == '':
   2008                 format = self.get_default_filetype()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\backend_bases.py in _get_output_canvas(self, fmt)
   1940         """
   1941         Return a canvas suitable for saving figures to a specified file format.
-> 1942
   1943         If necessary, this function will switch to a registered backend that
   1944         supports the format.

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\backend_bases.py in get_registered_canvas_class(format)
    120     """
    121     if format not in _default_backends:
--> 122         return None
    123     backend_class = _default_backends[format]
    124     if isinstance(backend_class, str):

~\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128
    129

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _load_unlocked(spec)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap_external.py in exec_module(self, module)

~\AppData\Local\Continuum\anaconda3\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\backends\backend_pdf.py in <module>
    421
    422
--> 423 class PdfFile(object):
    424     """PDF file object."""
    425

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\backends\backend_pdf.py in PdfFile()
    654
    655     @cbook.deprecated("3.0")
--> 656     @property
    657     def texFontMap(self):
    658         # lazy-load texFontMap, it takes a while to parse

~\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\cbook\deprecation.py in deprecate(obj, message, name, alternative, pending, addendum)
    180                 pass
    181     """
--> 182
    183     def deprecate(obj, message=message, name=name, alternative=alternative,
    184                   pending=pending, obj_type=obj_type, addendum=addendum):

AttributeError: 'property' object has no attribute '__name__'

[cid:image002.png@01D5ED87.6DD2B130]
. . .
In [ ]:

**Comment by taopeng1100** [comment] 2020-02-28 00:06
I did the 3 UMAPs in the error message on vdj_has_vdjdata, vdj_is_clone and leiden

**Comment by veghp** [comment] 2020-02-28 00:06
I mean, plot 'leiden' only. This way we can decide if the problem is with the plotting (scanpy) or the metadata column.

**Comment by taopeng1100** [comment] 2020-02-28 00:09
I got error message by just plotting leiden. I have never had this problem before. It happened only after I did pyvdj?

**Comment by veghp** [comment] 2020-02-28 00:29
I'm afraid this problem then most likely has nothing to do with pyVDJ, which just puts a pandas dataframe in the .uns dictionary, and annotation columns in the .obs dataframe. The code for each step is just a few lines: https://github.com/veghp/pyVDJ/blob/master/pyvdj/add_obs.py

You could test this by saving the current adata in a different file, restarting everything, then see if you can plot another adata which has not been altered by pyvdj. Then you can try again (skip the line `sc.settings.set_figure_params(dpi=70)`).

**Comment by taopeng1100** [comment] 2020-02-28 00:47
I am using Scanpy 1.4.4. It seems when enter the code:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scanpy as sc
import pyvdj
import random
from scipy import stats
import upsetplot
from matplotlib_venn import venn2
from matplotlib_venn import venn3


All the UMAP look different from my previous run like this:

import numpy as np
import pandas as pd
import scanpy as sc
%matplotlib inline
sc.settings.verbosity = 3             # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.logging.print_versions()
results_file = './write/Combine_SA_lesion+arm_191024.h5ad'  # the file that will store the analysis results


What do you think?

**Comment by taopeng1100** [comment] 2020-02-28 00:54
When I rerun in the following steps and it worked without error:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scanpy as sc
import pyvdj
import random
from scipy import stats
import upsetplot
from matplotlib_venn import venn2
from matplotlib_venn import venn3

I think we are using different versions of Scanpy. Can you update your pyvdj using 1.4.4?

**Comment by veghp** [comment] 2020-02-28 01:09
Your comment or what you have run is not clear to me, but `%matplotlib inline` is an important plotting function which is not in the first import block you posted. So, did the plotting work?

I don't think it's a version issue as pyVDJ was written using scanpy 1.4.3 and the next version is not much different: https://icb-scanpy.readthedocs-hosted.com/en/stable/release-notes.html#id2

**Comment by taopeng1100** [comment] 2020-02-28 02:31
The plotting works NOW. I really appreciate your patient in helping me out. The key is for me to restart the original analysis to generate adata and then do your pyvdj stuff. I try to go through you tutorial which focus on TCR distribution among different samples. I wonder if you can guide me a bit on how to analyze the clonal distribution among the different clusters in UMAP?

**Comment by veghp** [comment] 2020-02-28 11:06
No problem, I'm happy that I could help. I found the _Clone count_ section the most useful for my dataset.

If you want to look at _Clonotype distribution_, you can use everywhere
`meta = 'leiden'`
instead of 'metadata' or 'donor' as in the example.

Also in the _Expanded clonotypes_ section you run the commands with 'leiden':
`exp_counts = obs_vdj_df.groupby(['leiden']).vdj_expanded_n_2.value_counts()`
In the plotting command, you will have to set as many colours (with text or HEX code) as many categories (clusters) you have:
`p1 = plt.bar(ind, expanded, width, color=['blue', '#EF8536', '#EF8536'])`

It's probably helpful if you annotate the clusters first, i.e. assign cell types, and use that metadata category instead of leiden. 10x VDJ data gives information about the CDR3 sequences of each chain, but it doesn't tell you which two CDR3s are combined in a TCR, and this makes it hard to analyse the dataset.

**Comment by taopeng1100** [comment] 2020-02-28 19:45
I am interested in seeing the dominant clonotypes in each leiden cluster and how they overlap?
What should I do to implement that?

**Comment by taopeng1100** [comment] 2020-02-28 21:44
When I run this code: 
clonotypes = adata.obs['vdj_clonotype_gt_10'].unique()[2:].tolist()
cdr3_dict = pyvdj.get_spec(adata, clonotypes)
cdr3_dict

The error message is:
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2656             try:
-> 2657                 return self._engine.get_loc(key)
   2658             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'vdj_clonotype_gt_10'

**Comment by veghp** [comment] 2020-02-29 11:48
The error says you don't have that column in adata.obs. Each annotation column has to be made first;
`adata = pyvdj.add_gt_n(adata, n=10)`

**Comment by veghp** [comment] 2020-02-29 11:49
Another solution is to group your adata.obs dataframe by 'leiden', then sort by 'vdj_clone_count':
https://stackoverflow.com/questions/41825978/sorting-columns-and-selecting-top-n-rows-in-each-group-pandas-dataframe
then look at the 'vdj_clonotype' column.

To find common elements (clonotypes) between the clusters you can try something like that:
https://stackoverflow.com/questions/51079412/get-common-values-within-multiple-groupby-in-pandas-dataframe

**Comment by taopeng1100** [comment] 2020-02-29 17:54
I did:
adata = pyvdj.add_gt_n(adata, n=10)
clonotypes = adata.obs['vdj_clonotype_gt_10'].unique()[2:].tolist()
cdr3_dict = pyvdj.get_spec(adata, clonotypes)
cdr3_dict

Then I go the error message:
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2656             try:
-> 2657                 return self._engine.get_loc(key)
   2658             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'vdj_clonotype_gt_10'

**Comment by veghp** [comment] 2020-03-01 12:45
I see the problem now. The correct columname is 
`clonotypes = adata.obs['vdj_clonotype_n_10'].unique()[2:].tolist()`
as in the plotting function a few lines above it.
The function was changed at some point but this line in the tutorial wasn't updated.
Thanks for bringing attention to this. I'll include this in the next update of the tutorial.

**Comment by taopeng1100** [comment] 2020-03-01 17:23
I am going to meet with a python expert in my institute to help me get clonotypes associated with each Leiden cluster. Your last e-mail will be very helpful. Is there anything you advise me to get most out of my meeting? Thx

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by veghp** [comment] 2020-03-01 23:19
Perhaps my comment above https://github.com/veghp/pyVDJ/issues/3#issuecomment-592937260 will be the most helpful. Then you can obtain the CDR3 sequences, gene usage, or perhaps perform differential gene expression analysis on the GEX (mRNA) data.

Here is a good overview of the anndata: https://anndata.readthedocs.io/en/stable/
All VDJ data is stored as an entry in the .uns dictionary, and the structure is explained here: https://github.com/veghp/pyVDJ#load-vdj-data

**Comment by taopeng1100** [comment] 2020-03-03 20:05
I tried to talk to the guy in my institute to help me to grouby ‘leiden’ and then sort by vdj_count_count. We could not get this job done. Can you help? Ultimately, how can I compare the top clonotypes in each leiden cluster?

**Comment by veghp** [comment] 2020-03-04 00:23
Please note that 'vdj_count_count' is not a valid column, I hope this was not the error.

But yes it takes a bit of searching to figure out pandas. You can try:
`adata.obs[['leiden', 'vdj_clonotype', 'vdj_clone_count']]`
These are the columns we need. Save as a variable:
`obs = adata.obs[['leiden', 'vdj_clonotype', 'vdj_clone_count']]`
Group, get the count for each clonotype, sort then get the top 10 for each leiden group:
`top_n_by_cluster = obs.groupby(['leiden', 'vdj_clonotype']).size().sort_values(ascending=False).groupby(['leiden']).head(10)`
Save to csv:
`top_n_by_cluster.to_csv('top_n_by_cluster.csv')`

For seeing which clonotypes are in which cluster:
`s = obs.groupby('vdj_clonotype')['leiden'].apply(list)`
`print(s)`
but note that with n=6 clusters you have n(n-1)/2 = 15 comparisons.

I hope this helps, but unfortunately I don't work in this field anymore. I'll try and update the tutorial, but in any case, data analysis questions are well outside the scope of this (bug report) page, so I'll close this issue.

**Comment by taopeng1100** [comment] 2020-03-04 00:26
Many thx! I am figuring out slowly.

**Comment by taopeng1100** [comment] 2020-04-17 19:02
Hi Peter, I got 5’ gene expression and TCR vdj data from a single person with three cervix biopsies from different time points. I plan to concatenate adata. What is the way to link all the TCR vdj data to concatenated adata? I had hard time to do manifest part in your tutorial before!

I sincerely appreciate you help and take care in this COVID-19 era!

Tao

**Comment by nicoac** [comment] 2020-04-17 19:30
Dear Tao,

This is how I set mine up. But I'm having issues with the load_vdj command:

`samples = {directory path' : 'sample name'}`

**Comment by taopeng1100** [comment] 2020-04-17 19:37
Hi yes, I can do what you just said in single sample. Load_vdj is fine with me. But I am not sure how to load three vdj csv files to concatenated adata?

**Comment by veghp** [comment] 2020-04-19 14:00
You can list all samples with their paths, as shown in the tutorial:
```
samples = {
   'VDJ_TK_cx_8wks_191106/filtered_contig_annotations.csv': 'yoursampleid1',
   'VDJ_TK_cx_8wks_SECONDSAMPLE/filtered_contig_annotations.csv': 'yoursampleid2',
   'VDJ_TK_cx_8wks_THIRDSAMPLE/filtered_contig_annotations.csv': 'yoursampleid3',
}
```

**Comment by veghp** [comment] 2020-04-19 14:01
Perhaps you may also want to look at scirpy, for analyzing TCR data with scanpy: https://icbi-lab.github.io/scirpy/

**Comment by veghp** [comment] 2020-04-19 14:10
I may try and update pyVDJ sometime, but perhaps in the meantime you may want to look at scirpy, an another package for analyzing TCR data with scanpy: https://icbi-lab.github.io/scirpy/

**Comment by taopeng1100** [comment] 2020-04-19 16:44
I  appreciate your help!

**Closed as completed** 2020-07-03 11:24 UTC
